### ISSUE TITLE
ThreadSeperateImage not being updated from CheckAspectRatio

### ISSUE THREAD

**Issue by MrArca9** [devkanro/Meta.Vlc#206]
I noticed the video player being updated in size via checkaspectratio, which works fine when using the wpf:VlcPlayer , however when trying to use threadSeperateImage the resize never affects it and it keeps it's strange aspect ratio even though it was resized.

**Comment by higankanshi** [comment]
Yes, you can see this wiki 'https://github.com/higankanshi/Meta.Vlc/wiki/Use-VlcPlayer-with-other-controls', I did a lot optimization for it.
