### ISSUE TITLE
get bitmap from "libvlc_media_player_get_hwnd"

### ISSUE THREAD

**Issue by Mamad4D** [devkanro/Meta.Vlc#281]
hi,
as you know "libvlc_media_player_set_hwnd" method in winForm can redirect all frames output to a "Control" such as PictureBox or Panel. 

**how we can access to bitmap Which is being displayed in "Control"?**

Unfortunately :
"Bitmap bit = panel1.BackgroundImage;" returned null value.
also
            {
            Image bit = Image.FromHbitmap(panel1.Handle);
            panel1.BackgroundImage = bit;
            }
has error.

**Comment by devkanro** [comment]
We don't use hwnd to display video frame in Meta.Vlc, If you want to use vlc with WinForm, maybe you can try Vlc.DotNet or libvlcnet
